import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Container from "@/components/container/Container";
import Navbar from "@/components/commons/Navbar/Navbar";
import Footer from "@/components/commons/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tronix",
  description: "Generated by Emon",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container>
          <Navbar />
        </Container>
        {children}
        <Footer />
      </body>
    </html>
  );
}
